image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies and build
    init: |
      # Ensure clean install
      rm -rf node_modules package-lock.json
      # Use npm 11 (Dockerfile already installs it)
      npm install
      # Install sass explicitly for frontend
      cd frontend && npm install -D sass && cd ..
      # Build all workspaces
      npm run -ws build
    command: npm run -ws dev

ports:
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - Vue.volar
