image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies and build
    tasks:
  - init: |
      rm -rf node_modules frontend/node_modules package-lock.json
      npm cache clean --force
      npm install
    command: npm run -ws dev

ports:
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - Vue.volar
