image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install and build
    init: npm ci && npm run -ws build
    command: npm run -ws dev

ports:
  - port: 5173
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - Vue.volar

