openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /api/echo:
    post:
      summary: Echo message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Echoed message
          content:
            application/json:
              schema:
                type: object
                properties:
                  echo:
                    type: string
        '400':
          description: Validation error
