version: "3.9"

services:
  backend:
    env_file:
      - ../.env
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - swagger

  frontend:
    env_file:
      - ../.env
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0 --port ${FRONTEND_DEV_PORT:-5173}
    ports:
      - "${FRONTEND_DEV_PORT:-5173}:${FRONTEND_DEV_PORT:-5173}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  swagger:
    env_file:
      - ../.env
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ../backend/src/openapi.yaml:/openapi/openapi.yaml:ro
    ports:
      - "${SWAGGER_PORT:-8080}:8080"

networks:
  default:
    name: vue3-node-pro-template

